version: 2

project_name: hawkdog

before:
  hooks:
    - go mod tidy

builds:
  - id: hawkdog
    main: ./cmd/sentinel-watch
    binary: hawkdog
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    format: tar.gz
    files:
      - LICENSE
      - README.md
      - systemd/**
      - scripts/**

checksum:
  name_template: 'checksums.txt'

release:
  prerelease: auto

changelog:
  use: github
  sort: asc
